### ISSUE TITLE
USV Information zu LoxBerry und NAS

### ISSUE THREAD

**Issue by wick0310** [Woersty/LoxBerry-Plugin-APC-UPS#2]
Hallo

Ein frage das Plug-In finde ich richtig gut zuvor habe ich die USV über USB an meiner NAS ( Synology DS213j )angeschlossen um bei einem Stromausfall die NAS nach einer gewissen Zeit herunter zu fahren was ja auch nicht schlecht ist . Jetzt meine Frage gibt es eine möglichkeit beide geräte mit der Info der USV zu versorgen? ist es irgendwie möglich denn USB Anschluss zu Klonen am Loxberry ? um auch die NAS per USB an den Loxberry zu hängen ? leider kenne mich da nicht so gut aus oder kann der Loxberry die Info von der USV per Netzwerk an die NAS geschickt werden denn die Einstellmöglichkeit habe ich bei der NAS ich hoffe du kannst mir da helfen

![usv](https://cloud.githubusercontent.com/assets/22304429/26560511/7f20b4da-44b7-11e7-9227-303cc626a5d5.PNG)
![usv1](https://cloud.githubusercontent.com/assets/22304429/26560541/c7db9f46-44b7-11e7-8e5d-95640b6418c8.PNG)

**Comment by Woersty** [comment]
Das sollte eigentlich von Hause aus funktionieren.
Im Default ist die Koniguration
NETSERVER on
NISIP 0.0.0.0 => Er lauscht auf alle IPs des LoxBerry
NISPORT 3551

Viele Grüße
